{% set name = "sqlalchemy_exasol" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 062d4f2571f43c5a342ca1b3f8a5a87c597848dd008fa04a65700af541d34307

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry >=1
    - setuptools_scm
  run:
    - packaging >=21.3
    - pyexasol >=0.26.0,<1
    - python >={{ python_min }}
    - sqlalchemy >=1.4,<2
    - pyodbc >=4.0.34,<6
    - six >=1.5

test:
  requires:
    - python {{ python_min }}
  imports:
    - sqlalchemy_exasol

about:
  home: http://github.com/blue-yonder/sqlalchemy_exasol
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: SQLAlchemy dialect for EXASOL

extra:
  recipe-maintainers:
    - xhochy
