{% set name = "sqlalchemy_exasol" %}
{% set version = "4.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03a424886cc90480a2127ca0531779e8b0a415d4b113d85dd23025d6c0b52cd3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry >=1
    - setuptools_scm
  run:
    - packaging >=21.3
    - pyexasol >=0.25.1,<0.26.0
    - python >=3.7
    - sqlalchemy >=1.4,<2
    - pyodbc >=4.0.34,<6
    - six >=1.5

test:
  imports:
    - sqlalchemy_exasol

about:
  home: http://github.com/blue-yonder/sqlalchemy_exasol
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: SQLAlchemy dialect for EXASOL

extra:
  recipe-maintainers:
    - xhochy
