{% set name = "sqlalchemy_exasol" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d7542c4b0b0c1a2fd6309e5d3092af9fb0d57ea4ab75b55e86416176e0c3d609

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - sqlalchemy >=1.0.4,<1.4
    - pyodbc >=4.0.32
    - six >=1.5

test:
  imports:
    - sqlalchemy_exasol

about:
  home: http://github.com/blue-yonder/sqlalchemy_exasol
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: SQLAlchemy dialect for EXASOL

extra:
  recipe-maintainers:
    - xhochy
