{% set name = "sqlalchemy_exasol" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2ba5c792d9a78ac9fdc28a9138e3344a5326c5a4aa0a6f0dc016bfa4736681b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - sqlalchemy >=1.0.4,<2
    - pyodbc >=3.0.6
    - six >=1.5

test:
  imports:
    - sqlalchemy_exasol

about:
  home: http://github.com/blue-yonder/sqlalchemy_exasol
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'SQLAlchemy dialect for EXASOL'

extra:
  recipe-maintainers:
    - xhochy
