travis:
  secure:
    BINSTAR_TOKEN: 1NeEpat5V9UR9xqtlutZr+8gbte0y28nIM+61Z5gD8x0N7AuM9dp6lrynn9ri/AudzgBnaXypF8ByLlpxguaB4HXI0O1SkHnMBDH4tUB4YKZ9vEU1R4fP49vixKt/FZjTJxM3EDpDu/rSw6DxrRh64F0hBeBU1DaDXCd/yg0b5BMF/wvbvUgZ8BDP1BKk1jTvMsn0eeh9KlNLFdQzygR/QaRn4REhxoFkLwNRzMPLX++adD4mE2G1v03bV4FVwtPbKsO3KbKiHkPM3585KqMziQsTHxqtiMB2VCnvsIMEm6yAsD2d7x4E2NWsMzHd2MQVPMJlnVPVhziDCPcMjQrJKeHaUgdJriyNXLL9TZ+nKF34LUUNi7YXXjxAP29xV+zZ10jiNRTfajYaXXXUk6rpJzry2lZCuptPNq9TZZpD/qnjJAVFO+A2rnQ/myJuq0sDs5WienSi+E6rehhtE0GUSfZs6KrQcfKsQW0tXeKd9/dnmNzCh7cz8CTzf9z5wbPl1prlFiv/EXrr80K0H1O//6NhltQ9LOba3q1yjX9ePFyvBz45bROMWnXzYqqLBlT/HFVeRLULu45fK4SgK4je1xaLJf/5WDobzk38of5B1s36k+GFMo3oYFDUE25n8nhn2CykBrUWMDWKM2ac/i7mBRCS8gAo1LWBhYVctokYTA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
